import type { Metadata } from "next";
import { Arimo, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import SidebarLeft from "../components/SidebarLeft";

// Load Arimo (Sans font)
const arimo = Arimo({
  subsets: ["latin"],
  variable: "--font-arimo",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

// Load Roboto Mono (Monospace font)
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Docs - Boot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arimo.variable} ${robotoMono.variable} antialiased bg-[#0F0F0F] text-white`}
      >
        {/* 🔝 Fixed Navbar */}
        <header className="fixed top-0 left-0 right-0 h-[70px] bg-[#0F0F0F] border-b border-[#fff]/10 flex items-center px-6 md:px-20 z-50">
          <Navbar />
        </header>

        <div className="container flex gap-10">
          <div className="w-[20%] h-screen bg-[#0F0F0F] fixed top-0 items-center">
            <div className="flex items-center justify-center w-full"><SidebarLeft /></div>
          </div>

          <div className="ml-[320px] w-full mx-auto z-20">
            {children}
          </div>

        </div>

      </body>
    </html>
  );
}
